import Link from "next/link"
import { Navigation } from "@/components/Navigation"

export const metadata = {
  title: "Terms of Service — Project Rosie",
}

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navigation />
      <main className="flex-1 max-w-2xl mx-auto w-full px-5 sm:px-6 pt-28 pb-16">
        <div className="mb-10">
          <h1 className="text-3xl font-bold mb-2" style={{ fontFamily: "var(--font-dm-sans), sans-serif" }}>
            Terms of Service
          </h1>
          <p className="text-muted-foreground text-sm">Last updated: May 2026</p>
        </div>

        <div className="prose prose-sm max-w-none space-y-8 text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-foreground font-semibold text-lg mb-3" style={{ fontFamily: "var(--font-dm-sans), sans-serif" }}>
              1. Research Use Only
            </h2>
            <p>
              Project Rosie is a research and educational tool. All outputs — including ranked neoantigen
              candidates, clinical reports, and mRNA sequences — are generated by computational models
              and are intended solely for research purposes. Nothing produced by this platform constitutes
              medical or veterinary advice, diagnosis, or treatment.
            </p>
            <p className="mt-3">
              Do not make clinical decisions based solely on the output of this pipeline. Always consult
              a qualified veterinary or medical oncologist before taking any action.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-lg mb-3" style={{ fontFamily: "var(--font-dm-sans), sans-serif" }}>
              2. Submission Limits
            </h2>
            <p>
              Each account is entitled to 3 free pipeline runs. Additional submissions require prior
              approval. To request more runs, email{" "}
              <a href="mailto:shashank.padala@gmail.com" className="text-primary hover:underline">
                shashank.padala@gmail.com
              </a>{" "}
              with a short description of your use case.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-lg mb-3" style={{ fontFamily: "var(--font-dm-sans), sans-serif" }}>
              3. Data You Upload
            </h2>
            <p>
              By uploading a VCF file, you confirm that you have the right to share it and that it does
              not contain personally identifiable information about humans without appropriate consent.
              Uploaded files are stored securely in Google Cloud Storage and used only to run your
              requested pipeline job.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-lg mb-3" style={{ fontFamily: "var(--font-dm-sans), sans-serif" }}>
              4. No Warranty
            </h2>
            <p>
              This platform is provided &quot;as is&quot; without warranty of any kind. Computational
              predictions are probabilistic and may contain errors. We make no guarantees about the
              accuracy, completeness, or fitness for purpose of any pipeline output.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-lg mb-3" style={{ fontFamily: "var(--font-dm-sans), sans-serif" }}>
              5. Open Source
            </h2>
            <p>
              The pipeline and frontend code are open source and available on{" "}
              <a
                href="https://github.com/shashank-padala/project-rosie"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary hover:underline"
              >
                GitHub
              </a>
              . Use of the code is subject to the repository license.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-lg mb-3" style={{ fontFamily: "var(--font-dm-sans), sans-serif" }}>
              6. Changes
            </h2>
            <p>
              We may update these terms at any time. Continued use of the platform after changes
              constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-lg mb-3" style={{ fontFamily: "var(--font-dm-sans), sans-serif" }}>
              7. Contact
            </h2>
            <p>
              Questions? Email{" "}
              <a href="mailto:shashank.padala@gmail.com" className="text-primary hover:underline">
                shashank.padala@gmail.com
              </a>{" "}
              or reach out on{" "}
              <a
                href="https://linkedin.com/in/shashank-padala"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary hover:underline"
              >
                LinkedIn
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-10 pt-8 border-t border-border/50">
          <Link href="/privacy" className="text-primary text-sm hover:underline font-medium">
            Read our Privacy Policy →
          </Link>
        </div>
      </main>
    </div>
  )
}
