import { NextRequest, NextResponse } from "next/server"
import { marked } from "marked"
import { createServerClient } from "@/lib/supabase/server"

function fileSlug(name: string) {
  return name.replace(/[^a-z0-9]+/gi, "_").toLowerCase()
}

function printHtml(title: string, subtitle: string, sampleName: string, markdown: string, footer: string): string {
  const body = marked.parse(markdown) as string
  const date = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${sampleName} — ${title}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { font-size: 11pt; }
    body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; color: #111; line-height: 1.65; padding: 2.5cm 2.8cm; max-width: 21cm; margin: 0 auto; }
    h1 { font-size: 18pt; font-weight: 700; margin-bottom: 3pt; }
    h2 { font-size: 13pt; font-weight: 700; margin-top: 20pt; margin-bottom: 6pt; border-bottom: 1px solid #ddd; padding-bottom: 3pt; }
    h3 { font-size: 11pt; font-weight: 600; margin-top: 14pt; margin-bottom: 4pt; }
    p { margin-bottom: 8pt; }
    ul, ol { margin: 6pt 0 8pt 18pt; }
    li { margin-bottom: 3pt; }
    strong { font-weight: 600; }
    em { font-style: italic; color: #444; }
    code { font-family: "Courier New", monospace; font-size: 9.5pt; background: #f4f4f4; padding: 1px 4px; border-radius: 2px; }
    table { width: 100%; border-collapse: collapse; margin: 10pt 0 14pt; font-size: 10pt; }
    th { background: #f0f0f0; font-weight: 600; text-align: left; padding: 5pt 8pt; border: 1px solid #ccc; }
    td { padding: 5pt 8pt; border: 1px solid #ccc; vertical-align: top; }
    tr:nth-child(even) td { background: #fafafa; }
    .doc-header { border-bottom: 2px solid #111; padding-bottom: 12pt; margin-bottom: 20pt; }
    .doc-header-sub { font-size: 10pt; color: #555; margin-top: 2pt; font-style: italic; }
    .doc-meta { font-size: 9pt; color: #666; margin-top: 6pt; }
    .doc-footer { margin-top: 28pt; padding-top: 10pt; border-top: 1px solid #ddd; font-size: 8.5pt; color: #888; }
    @media print {
      body { padding: 0; }
      @page { margin: 2cm 2.5cm; size: A4; }
      h2 { page-break-after: avoid; }
      table { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="doc-header">
    <h1>${title}</h1>
    <div class="doc-header-sub">${subtitle}</div>
    <div class="doc-meta">Sample: <strong>${sampleName}</strong> &nbsp;·&nbsp; Generated by Project Rosie &nbsp;·&nbsp; ${date}</div>
  </div>
  ${body}
  <div class="doc-footer">${footer}</div>
  <script>window.onload = () => window.print();</script>
</body>
</html>`
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const supabase = await createServerClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return new NextResponse("Unauthorized", { status: 401 })

  const { id } = await params
  const type = req.nextUrl.searchParams.get("type")

  const { data: c } = await supabase
    .from("cases")
    .select("user_id, sample_name, clinical_report_md, mrna_fasta, mrna_summary_md")
    .eq("id", id)
    .single()

  if (!c || c.user_id !== user.id) return new NextResponse("Not found", { status: 404 })

  const slug = fileSlug(c.sample_name)

  if (type === "report-pdf" && c.clinical_report_md) {
    const html = printHtml(
      "Clinical Report",
      "Neoantigen Vaccine Candidate Analysis",
      c.sample_name,
      c.clinical_report_md,
      "Generated by Project Rosie. This report is intended to support clinical decision-making and must be reviewed by a qualified veterinary oncologist before use.",
    )
    return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8" } })
  }
  if (type === "fasta" && c.mrna_fasta) {
    return new NextResponse(c.mrna_fasta, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="${slug}_vaccine_mrna.fasta"`,
      },
    })
  }
  if (type === "synthesis-pdf" && c.mrna_summary_md) {
    const html = printHtml(
      "mRNA Synthesis Specification",
      "Personalized Neoantigen Vaccine — CMO Order Document",
      c.sample_name,
      c.mrna_summary_md,
      "All synthesis parameters require verification by a qualified formulation scientist before submission to a CMO. Dosing guidance requires veterinary oncologist sign-off prior to administration.",
    )
    return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8" } })
  }

  return new NextResponse("Not found", { status: 404 })
}
